{{- if .Values.role.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.role.name }}
  namespace : {{ .Values.namespace }}
rules: 
{{ toYaml .Values.role.rules  }}
{{- end -}}